<a href="https://colab.research.google.com/github/nkamble-aiml/Machine-Learning/blob/main/Day_38_Niraj_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### SimpleNeuron



```
constructor no of inputs, weights, bias  for z = mx + c

process


  if weights not given
    randon
  else
    take

  if bias not given
     zero
  else
     take input

  z = input * weights + bias

sigmoid( z score)
  1/(1+exp(z)
   
decide()
 process
 sigmoid
 return prob


```



In [41]:
import numpy as np
class SimpleNeuron:
    def __init__(self, no_of_inputs, weights=None, bias=None):


        self.no_of_inputs = no_of_inputs

        if weights is None:
            self.weights = np.random.rand(no_of_inputs) * 0.01
        else:
            self.weights = weights
        if bias is None:
            self.bias = np.zeros(1)
        else:
            self.bias = bias

        print("Inputs: ", no_of_inputs)
        print("Weights are : ", self.weights)
        print("Bias are : ", self.bias)

    def __process(self, inputs):
        print("inputs", inputs)
        z = np.dot(inputs, self.weights) + self.bias
        return z

    def __sigmoid(self, z):
        return 1 / (1 + np.exp(-z)), z

    def decide(self,inputs, threshold = 0.5):
      z_score = self.__process(inputs)
      prob = self.__sigmoid(z_score)
      print(prob[0])
      print(threshold)
      if prob[0] < threshold:
        return "You can touch"
      else:
        return "Hot!!!, Do not touch"


oneNeu = SimpleNeuron(no_of_inputs=1)
decision = oneNeu.decide(-0.1)
print("Decision: ", decision)


Inputs:  1
Weights are :  [0.00067749]
Bias are :  [0.]
inputs -0.1
[0.49998306]
0.5
Decision:  You can touch


In [1]:
class TouchDecisionNeuron(SimpleNeuron):
    def __init__(self,inputs):
        #Temperature -2 to 2
        #Familarity  0 - Unknow , 1 - Knows
        self.inputs = inputs
        weights = [-2.0,1]
        bias = 0.0
        super().__init__(no_of_inputs=2, weights=weights, bias=bias)

    def shoould_i_tounch(self):
      print(self.decide(self.inputs))


touch = TouchDecisionNeuron(inputs=[-0.1,0.0])
touch.shoould_i_tounch()


NameError: name 'SimpleNeuron' is not defined

In [1]:
def softmax(z):
  a = np.exp(z)
  sumOfZ = np.sum(a)
  return a/sumOfZ

In [13]:
import numpy as np
np.zeros_like(3)

array(0)

In [16]:
import numpy as np
np.random.seed(2)

#independent variables
X = np.array(eval(input()))
#dependent variable
y = np.array(eval(input()))

m = X.shape[0]  #no. of samples
n = X.shape[1]  #no. of features
arr = []
for sample in range(m):
  feature = X[sample]
  c =    1 #no. of classes in the data and therefore no. of neurons in the layer

  #weight vector of dimension (number of features, number of neurons in the layer)
  w = np.random.randn(n, 1)

  #bias vector of dimension (1, number of neurons in the layer)
  b = np.zeros((1, 1))

  #(weighted sum + bias) of dimension (number of samples, number of classes)

  print("feature :", feature)
  print("Weight :", w)
  print("base :", b)
  z = np.dot(feature,w) + b

  #exponential transformation of z
  a = np.exp(z)
  print("a: ",a)
  #print("Z: ",z)
  st = np.sum(a)
  print("sum(a): ",st)
  #Perform the softmax on a
  a = a / st

  #calculate the label for each observation
  y_hat = np.sum(a)
  arr.append(y_hat)
  #print(y_hat.astype(int))
print(arr)

[[100, 129, 157, 133], [168, 150, 30, 19], [4, 148, 106, 74], [123, 195, 60, 93], [169, 40, 188, 179], [40, 59, 29, 94], [165, 126, 16, 99], [167, 157, 65, 23], [128, 87, 37, 111], [191, 154, 89, 134], [101, 41, 145, 112], [43, 110, 197, 118], [147, 22, 109, 139], [11, 161, 135, 119], [26, 48, 199, 182], [96, 100, 82, 87], [149, 2, 8, 10], [5, 38, 166, 100], [193, 117, 59, 164], [133, 5, 38, 163], [88, 177, 84, 114], [9, 132, 177, 24], [94, 130, 83, 131], [77, 11, 141, 81], [154, 198, 175, 98], [21, 148, 170, 122], [185, 145, 101, 183], [100, 196, 111, 11], [97, 147, 112, 11], [25, 97, 95, 45], [6, 89, 88, 38], [51, 16, 151, 3], [90, 174, 122, 157], [2, 133, 121, 199], [15, 78, 163, 180], [103, 118, 7, 179], [102, 179, 157, 183], [113, 139, 195, 122], [55, 88, 68, 117], [115, 185, 93, 102], [139, 82, 3, 165], [135, 29, 78, 11], [11, 16, 60, 123], [103, 191, 187, 129], [146, 181, 28, 192], [85, 73, 136, 139], [117, 179, 81, 183], [15, 131, 106, 28], [58, 78, 111, 65], [76, 11, 25, 103],

/tmp/ipython-input-3237117685.py:30: RuntimeWarning: overflow encountered in exp
  a = np.exp(z)
/tmp/ipython-input-3237117685.py:36: RuntimeWarning: invalid value encountered in divide
  a = a / st


In [67]:
class SimpleNeuralNetwork:
    def __init__(self, input_features, output_class, learning_rate=0.1):
        self.input_features = input_features
        self.output_class = output_class
        self.learning_rate= learning_rate
        # Weight array is created with random value based on input features and output class to be produced
        self.W = np.random.randn(self.input_features, self.output_class) * 0.1
        self.b = np.zeros((1, self.output_class))

        print("Random Weights: ", self.W)
        print("Random Bias: ", self.b)

    def forwardPropogation(self, features):
       self.X = np.array(features)
       self.Z = np.dot(self.X, self.W) + self.b
       self.A = self.softmax(self.Z)

       for sample in range(len(self.A)):
        print(f"Sample Probability {sample+1}: {self.A[sample]}")



    def softmax(self,Z):
      self.A = np.exp(Z) / sum(np.exp(Z))
      return self.A

    def logLoss(self,Y_TRUE_INDEX):
      print("Y_TRUE_INDEX",Y_TRUE_INDEX)

      m = len(self.Z)

      losses = -np.log(self.A[range(m),Y_TRUE_INDEX])
      print("Losses: ", losses)

      for i in range(len(self.A)):
        print(f"For Sameple {i+1} :: -log( {self.A[i,Y_TRUE_INDEX[i]]} ) = {losses[i]}" )

      avg_loss = np.mean(losses)
      print("Average Loss ::", avg_loss)
      return losses

    def backwardPropogartion(self, Y_TRUE_INDEX):

      m = len(Y_TRUE_INDEX)
      print("m:",m)
      actual_label = np.zeros((m,self.output_class))
      actual_label[range(m),Y_TRUE_INDEX] = 1

      print("***" * 10)
      print("backward Propogation")
      print("Actual Value",actual_label)
      print("Probabilities Value",self.A)
      #weight error finding
      self.dZ = self.A - actual_label
      #find the Gradient Truth
      print("Delta Probabilities Value",self.dZ)
      self.dZ = self.dZ/m

      #calculate weight error
      self.dW = np.dot(self.X.T, self.dZ)
      print("Weight Error",self.dW)

      #calculate bias error
      self.db = np.sum(self.dZ, axis=0, keepdims=True)

      self.W = self.W - self.learning_rate * self.dW
      self.b = self.b - self.learning_rate * self.db
      print("Updated Weights",self.W)
      print("Updated Bias",self.b)

X = [[1.2,0.4],[-1.5,2.0]]
#0 - CAT
#1 - DOG
#2 - BIRD
Y_TRUE = [0,2]
simpleNN = SimpleNeuralNetwork(2,3,0.1)
simpleNN.forwardPropogation(X)
simpleNN.logLoss(Y_TRUE)
simpleNN.backwardPropogartion(Y_TRUE)


Random Weights:  [[-0.07052315  0.00564528 -0.10628081]
 [-0.03035815 -0.13337193 -0.16298055]]
Random Bias:  [[0. 0. 0.]]
Sample Probability 1: [0.46459947 0.55691163 0.49345305]
Sample Probability 2: [0.53540053 0.44308837 0.50654695]
Y_TRUE_INDEX [0, 2]
Losses:  [0.76657961 0.68013826]
For Sameple 1 :: -log( 0.4645994657299209 ) = 0.766579608603612
For Sameple 2 :: -log( 0.5065469503552635 ) = 0.6801382639225189
Average Loss :: 0.7233589362630655
m: 2
******************************
backward Propogation
Actual Value [[1. 0. 0.]
 [0. 0. 1.]]
Probabilities Value [[0.46459947 0.55691163 0.49345305]
 [0.53540053 0.44308837 0.50654695]]
Delta Probabilities Value [[-0.53540053  0.55691163  0.49345305]
 [ 0.53540053  0.44308837 -0.49345305]]
Weight Error [[-0.72279072  0.0018307   0.66616162]
 [ 0.42832043  0.5544707  -0.39476244]]
Updated Weights [[ 0.00175592  0.00546221 -0.17289697]
 [-0.0731902  -0.188819   -0.12350431]]
Updated Bias [[ 5.55111512e-18 -5.00000000e-02  0.00000000e+00]]


In [7]:
import numpy as np

#arr = [[0,0,0],[0,0,0]]
#np.zeros_like(arr)


np.random.randn(2, 3)


array([[-0.13458558,  1.32788433,  0.50240044],
       [ 0.69847609,  0.47990559,  0.77262572]])

In [19]:
arr = np.zeros((1,3))
arr.shape
print(arr)

[[0. 0. 0.]]


In [53]:
m=2
print(range(m))
arr = [
        [1,2],
        [3,4]
      ]
npArr = np.array(arr)
npArr[range(0,2),1]

range(0, 2)


array([2, 4])